services:
  chatbot-backend:
    build:
      context: ./chatbot-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - chatbot-server/.env
    networks:
      - chatbot-network

  c-app:
    build:
      context: ./chatbot-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge